//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptOX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6545")]
        public string ipx {
            get {
                return ((string)(this["ipx"]));
            }
            set {
                this["ipx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5050")]
        public int porrt {
            get {
                return ((int)(this["porrt"]));
            }
            set {
                this["porrt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJ" +
            "C4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAAyAD0BAREA/8QAGwAAAgMBAQEAAAAAAAAAA" +
            "AAAAAYEBQcIAwL/xAAwEAACAQMEAQIEBgEFAAAAAAABAgMEBREABhIhMUFhBxMiURQVIzJCcRYzcoGh4" +
            "f/aAAgBAQAAPwDf9GjOjRnRo0a+XdY42d2CooyWY4AH3Oudbxvq8b6vtxkpNxS2HbFBkCWBiryjPEMSM" +
            "ElvtnCjHr5qYtxWGZHhi3LfECfQZp7hMWY4PY+tR/0ffI15UsF6mu1YKHdV2/LlpmYTPXyIA/EkfMPPo" +
            "DBOR7ffOoFv3AsVJD+ZX+vEzHHNbjLM3uxCyAD2BHjTJbr3aLpMKa37lvVLWf6aSJcJ2LHzzPJiAvp7e" +
            "oA71r2wN1TXmCrs91lja9Wxgk5Uj9aMjKS4HQJHTAdA+xGnTWL/ABV3ZVSy3qzKzQ0FvjiWeNQc1TSIX" +
            "wzAgiMAAYH7jnJwMHD9xJHS1slD86ESUvET08fJYXkAHIpjrv18ZxkasarcNNJfXv8ARWORLb8j5MlA0" +
            "QNMhMfDjyAxxz9QyAc+ue9Mvwvst2oIL9JV2+sp4qq3GOnPHizy98QoPTHPofOlF3lpNsptuosdVSXU1" +
            "X4hJ44frqBxxwYH6jx8jievUZ71WXi7/mFfBULS/hTHBHA7DppWQYLtjH1H1/rTnsuhlV0vdlugpxRKw" +
            "MyxiKZW5LkOuTzBVsrnIPEqQDgjpXaN9/ybalvvBi+U1THll9AwJU49iQSPYjSl8TdjPeYZb3boFqKyO" +
            "nMNXRN0tbADy4gj9si9lG+/R61zhdbrBHuCmro/l3FDTJHN8+IgTDBTvP8ALiF+oeGGfTV1Zr1aBRtb/" +
            "wAwrdvSyqkdWoJkppQCFYvF2CSuSevI/wCDOnobNFQO9HuWxxTPUIiSiGSKURsAfmtwcjIJwBg4wfB17" +
            "rarHbqh66Xe1LHDHK9PJFaFEDyxiMNyQAn9xwpPWSMH1wo3eqs6Wh4rTb3YTvEZK2ZSxBC8mQFvDcj3j" +
            "yB5OdPmy9rTbso6Hb1JUGKhjhWS5TwAYCsebDI8yOwVO/CxE4wcHpC226ltNtprfRQrDS00axRRj+KgY" +
            "H96laxvf3wpg/EzXux0h5EiVoYFPOnlBLCSJR+5Sc8ox33le+jl1ZPZ7rSSzblSSmuUrxIksagpKrOTJ" +
            "NGcdkHAIJOB114E1Phvt2ora5IrvVxpTT0qcGCEhJXAYlusEKy+nn7jUea0bJ2rOrV4kucsNY9PPAJgx" +
            "ClCVIUYDfx7z0SR6d3MVj3B8Tq2ns9BQxWfblI6MQ8IVogFwGYeWdh6dZ8nA710BtrbVs2nZYbVaoBFB" +
            "H2Se2kb1dj6sf8AwdDVvo0aSt0fDW07jeWohke31kp5SvEivHMfvJEwKsffpvfSW3wJH6nKos0pdQufw" +
            "E0YGPB4pNjOp9q+Btsiljkuk9O6xuHCW+nanJI8AyF2bH+0r/etQoLdR2qjSkoaeOCBPCIMDPqT9yfUn" +
            "s6laNGjRo0aNGjX/9k=")]
        public string photb64 {
            get {
                return ((string)(this["photb64"]));
            }
            set {
                this["photb64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zder")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
    }
}
